name: secure_wave
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # device_policy_controller: 0.0.3+1
  device_admin_manager:
    git:
      url: https://github.com/iammujtaba44/DeviceAdminManager.git
  infinite_binary_ui_kit:
    git:
      url: https://github.com/infinite-binary/UI_Kit.git
  provider: ^6.1.2
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.3
  firebase_auth: ^5.3.2
  firebase_database: ^11.1.5
  get_it: ^8.0.2
  auto_route: ^9.2.2
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  workmanager: ^0.5.2
  device_info_plus: ^10.0.0
  video_player: 2.9.2
  cached_network_image: ^3.3.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.13
  auto_route_generator: 9.0.0
  freezed: 2.4.7 # Used for immutable models generation
  json_serializable: 6.8.0 # Used for json serialization
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
