name: device_admin_manager
description: A Flutter plugin package for managing device policies and restrictions (DPC), with features like kiosk mode app locking.
version: 0.0.1

topics:
  - dpc
  - device-management
  - kiosk

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        minSdkVersion: 21
        package: com.ib.device_admin_manager
        pluginClass: DeviceAdminManagerPlugin
